<?phpinclude_once("../config/symbini.php");header("Content-Type: text/html; charset=".$CHARSET);header("Cache-Control: no-cache, must-revalidate"); // HTTP/1.1header("Expires: Sat, 26 Jul 1997 05:00:00 GMT"); // Date in the past?><html><head>    <title><?php echo $DEFAULT_TITLE?> Meetings</title>    <link rel="shortcut icon" href="favicon.ico" type="image/x-icon"/>    <link rel="stylesheet" href="../css/base.css" type="text/css" />    <link rel="stylesheet" href="../css/main.css" type="text/css" />    <meta name='keywords' content='' />	<script type="text/javascript">		<?php include_once('includes/googleanalytics.php'); ?>	</script></head><body>	<?php	$displayLeftMenu = false;	include($SERVER_ROOT.'/includes/header.php');	?>        <!-- This is inner text! -->        <div  id="innertext">        	<div>            	<h1>Meetings</h1>				<hr /> 				<div> 				<p>&nbsp;</p><p><strong style="font-size: 1.2em;">CNH 2020</strong></p><hr /><p><a href="https://peabody.yale.edu/collections/botany"><img class="floatRightwrap" title="YU Logo" src="../images/collicons/YU_logo_300.gif" alt="YU Logo" width="100" /></a>The 2020 Consortium of Northeastern Herbaria (CNH) annual meeting was scheduled be held at <a title="Yale Meyers" href="https://forests.yale.edu/about/facilities" target="_blank">Yale-Meyers Forest</a> on June 19 and 20. Taking into consideration the projections that COVID-19 disruptions and restrictions may continue well into the summer and with the health and safety of our membership in mind, we regret to announce that the 2020 CNH meeting, in its current form, is cancelled. Thanks very much for your understanding.</p><p>Stay safe and healthy.</p><p>If you have any questions contact Patrick Sweeney (patrick.sweeney@yale.edu).</p>

				<p>&nbsp;</p><p><strong style="font-size: 1.2em;">CNH 2019</strong></p><hr /><p><a href="https://www.idigbio.org/wiki/index.php/3rd_Annual_Digital_Data_Conference,_Yale"><img class="floatRightwrap" title="YU Logo" src="../images/collicons/YU_logo_300.gif" alt="YU Logo" width="100" /></a>The 2019 Consortium of Northeastern Herbaria (CNH) annual meeting was hosted by the Yale University Herbarium and was held in conjunction with the <a href="https://www.idigbio.org/wiki/index.php/3rd_Annual_Digital_Data_Conference,_Yale" target="_blank">3rd Annual Digital Data in Biodiversity Research Conference</a>. This meeting provided a great opportunity for herbarium curators and collection managers to learn how biodiversity collection data is being used for research, to learn about digital data tools and techniques, and to meet the users of digital data. The CNH business meeting will be held at the end of the day on Monday, June 10.</p>

 					<p>&nbsp;</p><p><strong style="font-size: 1.2em;">CNH 2018</strong></p><hr /><p><a href="http://www.unh.edu/herbarium/"><img class="floatRightwrap" title="NHA Logo" src="icons/UNewHampshire_seal.png" alt="UNH Logo" width="100" /></a>The 2018 Consortium of Northeastern Herbaria annual meeting was hosted by the <a title="UNH Herbarium" href="http://www.unh.edu/herbarium/" target="_blank">University of New Hampshire Hodgdon Herbarium</a> and held on June 13 &amp; 14 in Concord &amp; Manchester, New Hampshire. This meeting was different from previous meetings in that it consisted primarily of field collecting activity (vascular plants and/or bryophytes)&nbsp;in natural areas in the vicinity of Concord. There was a business meeting and presentation on the evening of June 13.</p>

 					<p>&nbsp;</p><p><strong style="font-size: 1.2em;">CNH 2017</strong></p><hr /><p><a href="https://www.eaglehill.us"><img class="floatRightwrap" title="NENHC Logo" src="icons/NENCH-2017.jpg" alt="NENHC Logo" width="100" /></a>The 2017 Consortium of Northeastern Herbaria meeting was held in conjunction with the Northeast Natural History Conference (NENHC) in Cromwell, Connecticut during April 21 - 23. The NENHC is an annual meeting that brings together researchers, field biologists, natural resource managers, academics, etc. to share information on all aspects of the natural history sciences of the northeastern United States and eastern Canada. At this meeting, CNH hosted a session entitled “<span style="text-decoration: underline;"><em>Herbarium collections as a resource for 21st century botany, ecology, and conservation</em></span>”. In addition to this session, there was be a business meeting.&nbsp;<span style="font-size: 14.3999996185303px; line-height: 18.7199993133545px;">Meeting minutes can be downloaded&nbsp;</span><strong><a href="minutes/MeetingMinutes2017.pdf" target="_blank">here</a></strong>.<p>&nbsp;</p>

 					<p><strong style="font-size: 1.2em;">CNH 2016</strong></p><hr /><p><a href="https://www.brown.edu/research/projects/herbarium/"><img class="floatRightwrap" title="Brown Logo" src="icons/Brown_University_Logo.gif" alt="Brown Logo" width="75" /></a>The 2016 Consortium of Northeastern Herbaria meeting is being hosted by the <a title="BRU Herbarium" href="https://www.brown.edu/research/projects/herbarium/" target="_blank">Brown University Herbarium</a> and will be held on June 29 &amp; 30 in Providence, Rhode Island at Brown University. There will be a single day of talks and business activities on Wednesday, June 29 and on Thursday, June 30 there will be demonstrations or a fieldtrip.&nbsp;Meeting minutes can be downloaded&nbsp;<strong><a href="minutes/MeetingMinutes2016.pdf" target="_blank">here</a></strong>.<p>&nbsp;</p>

 					<p><strong style="font-size: 1.2em;">CNH 2015</strong></p><hr /><p><a href="http://www.nybg.org/"><img class="floatRightwrap" title="NYBG Logo" src="icons/NYBG_logo.png" alt="NYBG Logo" width="100" /></a>The 2015 Consortium of Northeastern Herbaria meeting will be held on June 25 &amp; 26 at the New York Botanical Garden. There will be a single day of talks and business activities on Thursday, June 25 and workshops, demonstrations, and tours of the Garden on Friday, June 26. Visit the meeting page <a title="CNH 2015 meeting" href="CNH_2015" target="_self">here</a>.&nbsp;Meeting minutes can be downloaded&nbsp;<strong><a href="minutes/MeetingMinutes2015.pdf" target="_blank">here</a></strong>.</p><p>&nbsp;</p>

 					<p><strong style="font-size: 1.2em;">CNH 2014</strong></p><hr /><p><a href="http://www.irbv.umontreal.ca/"><img class="floatRightwrap" title="IRBV Logo" src="icons/logo-irbv1.png" alt="IRBV Logo" width="100" /></a>The 2014 Consortium of Northeastern Herbaria meeting was held at the Biodiversity Centre of the Université de Montréal just before the Canadian Botanical Association meeting of June 15-18, 2014. There was a single day of talks and business activities on Friday, June 13 and workshop activites were on Saturday, June 14. Meeting minutes can be downloaded <strong><a href="minutes/MeetingMinutes2014.pdf">here</a></strong>.</p>

 					<p>&nbsp;</p> <p><strong style="font-size: 1.2em;">CNH 2013</strong></p> <hr /><p><a href="http://www.uvm.edu/~plantbio/pringle/"><img class="floatRightwrap" title="UVM Logo" src="icons/uvmtower.jpg" alt="UVM Logo" width="75" /></a>The 2013&nbsp;Consortium of Northeastern Herbaria meeting was held during July 17-19 at the University of Vermont. A field trip to Mount Mansfield took place on Wednesday, July 17th. Talks and workshop activities were on Thursday (18th) and Friday (19th).&nbsp;Meeting minutes can be downloaded <strong><a style="font-size: 0.9em; line-height: 1.3em;" title="CNH 2015 minutes" href="minutes/MeetingMinutes2013.pdf" target="_blank">here</a></strong>.</p> <p>&nbsp;</p>

 					<p><strong style="font-size: 1.2em;">CNH 2012</strong></p> <hr /><p><a href="http://peabody.yale.edu/collections/spnhc2012/home"><img class="floatRightwrap" title="SPNHC Logo" src="icons/spnhc_logo.jpg" alt="SPNHC Logo" width="150" /></a>The Consortium of Northeastern Herbaria 2012 meeting was held in conjunction with the SPNHC 2012 annual meeting hosted by the Yale Peabody Museum of Natural History in New Haven, Connecticut during June 10 to June 16, 2012 (<a style="color: blue;" href="http://peabody.yale.edu/collections/spnhc2012/home" target="new">website</a>).</p> <p>Meeting minutes can be downloaded <a href="minutes/MeetingMinutes2012.pdf">here</a>.</p> <p>&nbsp;</p>

 					<p><strong style="font-size: 1.2em;">CNH 2011</strong></p> <hr /><p><a href="http://www.ansp.org/research/biodiv/botany/index.php"><img class="floatRightwrap" title="ANSP Logo" src="icons/ANS_Logo_Black.jpg" alt="ANSP Logo" width="150" /></a>The CNH 2011 meeting was held on June 6 &amp; 7 (Monday - Tuesday) at Academy of Natural Sciences of Philadelphia.  An additional day June 5 (Sunday) was devoted to field trips to regional botanical attractions.&nbsp;The meeting minutes are available here (<a href="minutes/CNHMeetingMinutes2011.pdf">.pdf</a>).</p><p>&nbsp;</p>

 					<p><strong style="font-size: 1.2em;">CNH 2010</strong></p> <hr /><p><img class="floatRightwrap" title="CBA-SPNHC Logo" src="icons/cba_2010.jpg" alt="CBA-SPNHC Logo" width="150" />The Consortium of Northeastern Herbaria 2010 meeting was held in conjunction with the SPNHC &amp; CBA-ABC joint conference in Ottawa, Ontario Canada during May 31 to June 5, 2010. &nbsp;The meeting minutes are available here (<a href="minutes/meetingminutes2010.pdf">.pdf</a>).&nbsp;</p> <p>&nbsp;</p>

 					<p><strong style="font-size: 1.2em;">CNH 2009</strong></p> <hr /><p>The Consortium of Northeastern Herbaria last met on June 8-9, 2009 at the University of New Hampshire in Durham. Our hosts were Chris Neefus and Janet Sullivan.  The meeting minutes are available here (<a href="minutes/Minutes2009.pdf">.pdf</a>).</p> <p>&nbsp;</p>

 					<p><br /> <strong style="font-size: 1.2em;">CNH 2008</strong></p> <hr /><p>The 2008 meeting was held at the University of Massachusetts at Amherst on June 2, 2008. Our host was Karen Searcy.  The meeting minutes are available here (<a href="minutes/meetingminutes2june2008.pdf">.pdf</a>).</p>
 				<div style="margin-bottom:20px;">
			</div>
		</div>
		<!-- end of inner text! -->		<?php		include($SERVER_ROOT.'/includes/footer.php');		?></body></html>